import Chronos.Frontier.SchwarzschildIngoingEFHorizon
import Chronos.Frontier.SchwarzschildNullPotentialMaximum
import Chronos.Frontier.ReggeWheelerFlagshipExactResidual
import Chronos.Frontier.DFMMKCNewtonianGaugeWeightedPerturbationEnergy
import Chronos.Frontier.DFMMKCChargeReducedRadialMomentumSourceBinding
import Chronos.Frontier.DFMMKCNewtonianGaugeEnergyControlledMarginEstimate

#print axioms Chronos.Frontier.schwarzschildOutgoingNullExpansion_eq_zero_iff
#print axioms Chronos.Frontier.schwarzschildNullEffectivePotential_unique_exterior_maximum
#print axioms Chronos.Frontier.reggeWheelerFlagship_exactResidualPackage
#print axioms Chronos.Frontier.dfmMkcNewtonianGauge_abs_momentumCombination_le_anchor_add_sourceControl
#print axioms Chronos.Frontier.dfmMkcNewtonianGauge_abs_momentumGateTerm_le_anchor_add_sourceControl
#print axioms Chronos.Frontier.dfmMkcPerturbedQLGate_le_hubbleFloor_add_absorbedEnergy
#print axioms Chronos.Frontier.dfmMkcNewtonianGauge_currentCarrier_violates_uniform_absorption