from pathlib import Path
lean = Path("lean/Chronos/Frontier/SelectedDomainFinalConditionalClosureBridge.lean").read_text()
artifact = Path("artifacts/external_validation/selected_domain_final_conditional_closure_bridge_2026_06_24.json").read_text()
doc = Path("docs/status/SELECTED_DOMAIN_FINAL_CONDITIONAL_CLOSURE_BRIDGE_2026_06_24.md").read_text()
assert "SelectedDomainFinalConditionalClosureBridge" in lean and "SelectedDomainFinalConditionalClosureBridge" in artifact and "SelectedDomainFinalConditionalClosureBridge" in doc
assert "SelectedDomainRepairDescentZeroDefectReentryNormalizationFinalClosureOblivionClosureTargetPrefix" in lean and "SelectedDomainRepairDescentZeroDefectReentryNormalizationFinalClosureOblivionClosureTargetPrefix" in artifact and "SelectedDomainRepairDescentZeroDefectReentryNormalizationFinalClosureOblivionClosureTargetPrefix" in doc
assert "SelectedDomainDefectAtomsConstructionTarget" in lean and "SelectedDomainDefectAtomsConstructionTarget" in artifact and "SelectedDomainDefectAtomsConstructionTarget" in doc
assert "SelectedDomainDefectSemanticComponentTargets" in lean and "SelectedDomainDefectSemanticComponentTargets" in artifact and "SelectedDomainDefectSemanticComponentTargets" in doc
assert "selected_domain_semantic_component_targets_from_final_bridge" in lean
assert "selected_domain_defect_atoms_target_from_final_bridge" in lean
assert "unrestricted_oblivion_atom_closure_statement_from_final_bridge" in lean and "unrestricted_oblivion_atom_closure_statement_from_final_bridge" in artifact and "unrestricted_oblivion_atom_closure_statement_from_final_bridge" in doc
assert "defect_atoms_construction_statement_from_final_bridge" in lean and "defect_atoms_construction_statement_from_final_bridge" in artifact and "defect_atoms_construction_statement_from_final_bridge" in doc
assert "terminal_cardinality_of_defect_atoms_from_final_bridge" in lean and "terminal_cardinality_of_defect_atoms_from_final_bridge" in artifact and "terminal_cardinality_of_defect_atoms_from_final_bridge" in doc
assert "zero_defects_imply_selected_domain_reentry_from_final_bridge" in lean and "zero_defects_imply_selected_domain_reentry_from_final_bridge" in artifact and "zero_defects_imply_selected_domain_reentry_from_final_bridge" in doc
assert "repair_step_decreases_or_preserves_defect_atoms_from_final_bridge" in lean and "repair_step_decreases_or_preserves_defect_atoms_from_final_bridge" in artifact and "repair_step_decreases_or_preserves_defect_atoms_from_final_bridge" in doc
assert "defect_atoms_transfer_through_terminal_normalization_from_final_bridge" in lean and "defect_atoms_transfer_through_terminal_normalization_from_final_bridge" in artifact and "defect_atoms_transfer_through_terminal_normalization_from_final_bridge" in doc
assert "selected_domain_defect_terminal_closure_component_discharge_from_semantic_targets" in lean
assert "unrestricted_oblivion_atom_closure_statement_from_semantic_component_targets" in lean
assert "defect_atoms_construction_statement_from_target" in lean
assert "BOUNDARY := not unconditional_unrestricted_oblivion_atom_closure_solved" in artifact and "BOUNDARY := not unconditional_unrestricted_oblivion_atom_closure_solved" in doc
assert "does not prove unconditional unrestricted Oblivion Atom closure" in doc
assert "does not claim that unrestricted Oblivion Atom closure is solved unconditionally" in doc
assert "SELECTED_DOMAIN_FINAL_CONDITIONAL_CLOSURE_BRIDGE_2026_06_24_OK" in doc
print("SELECTED_DOMAIN_FINAL_CONDITIONAL_CLOSURE_BRIDGE_2026_06_24_OK")
