from pathlib import Path
lean = Path("lean/Chronos/Frontier/SelectedDomainUnconditionalClosureConstructionInput.lean").read_text()
artifact = Path("artifacts/external_validation/selected_domain_unconditional_closure_construction_input_2026_06_24.json").read_text()
doc = Path("docs/status/SELECTED_DOMAIN_UNCONDITIONAL_CLOSURE_CONSTRUCTION_INPUT_2026_06_24.md").read_text()
assert "SelectedDomainUnconditionalClosureConstructionInput" in lean and "SelectedDomainUnconditionalClosureConstructionInput" in artifact and "SelectedDomainUnconditionalClosureConstructionInput" in doc
assert "final_conditional_closure_bridge" in lean and "final_conditional_closure_bridge" in artifact and "final_conditional_closure_bridge" in doc
assert "SelectedDomainFinalConditionalClosureBridge" in lean and "SelectedDomainFinalConditionalClosureBridge" in artifact and "SelectedDomainFinalConditionalClosureBridge" in doc
assert "SelectedDomainDefectSemanticComponentTargets" in lean and "SelectedDomainDefectSemanticComponentTargets" in artifact and "SelectedDomainDefectSemanticComponentTargets" in doc
assert "SelectedDomainDefectAtomsConstructionTarget" in lean and "SelectedDomainDefectAtomsConstructionTarget" in artifact and "SelectedDomainDefectAtomsConstructionTarget" in doc
assert "selected_domain_final_bridge_from_unconditional_construction_input" in lean
assert "selected_domain_semantic_component_targets_from_unconditional_construction_input" in lean
assert "selected_domain_defect_atoms_target_from_unconditional_construction_input" in lean
assert "defect_atoms_construction_statement_from_unconditional_construction_input" in lean and "defect_atoms_construction_statement_from_unconditional_construction_input" in artifact and "defect_atoms_construction_statement_from_unconditional_construction_input" in doc
assert "terminal_cardinality_of_defect_atoms_from_unconditional_construction_input" in lean and "terminal_cardinality_of_defect_atoms_from_unconditional_construction_input" in artifact and "terminal_cardinality_of_defect_atoms_from_unconditional_construction_input" in doc
assert "zero_defects_imply_selected_domain_reentry_from_unconditional_construction_input" in lean and "zero_defects_imply_selected_domain_reentry_from_unconditional_construction_input" in artifact and "zero_defects_imply_selected_domain_reentry_from_unconditional_construction_input" in doc
assert "repair_step_decreases_or_preserves_defect_atoms_from_unconditional_construction_input" in lean and "repair_step_decreases_or_preserves_defect_atoms_from_unconditional_construction_input" in artifact and "repair_step_decreases_or_preserves_defect_atoms_from_unconditional_construction_input" in doc
assert "defect_atoms_transfer_through_terminal_normalization_from_unconditional_construction_input" in lean and "defect_atoms_transfer_through_terminal_normalization_from_unconditional_construction_input" in artifact and "defect_atoms_transfer_through_terminal_normalization_from_unconditional_construction_input" in doc
assert "unrestricted_oblivion_atom_closure_statement_from_unconditional_construction_input" in lean and "unrestricted_oblivion_atom_closure_statement_from_unconditional_construction_input" in artifact and "unrestricted_oblivion_atom_closure_statement_from_unconditional_construction_input" in doc
assert "BOUNDARY := not selected_domain_unconditional_closure_construction_input_constructed" in artifact and "BOUNDARY := not selected_domain_unconditional_closure_construction_input_constructed" in doc
assert "BOUNDARY := not unconditional_unrestricted_oblivion_atom_closure_solved" in artifact and "BOUNDARY := not unconditional_unrestricted_oblivion_atom_closure_solved" in doc
assert "does not construct SelectedDomainUnconditionalClosureConstructionInput" in doc
assert "does not prove unconditional unrestricted Oblivion Atom closure" in doc
assert "does not claim that unrestricted Oblivion Atom closure is solved unconditionally" in doc
assert "SELECTED_DOMAIN_UNCONDITIONAL_CLOSURE_CONSTRUCTION_INPUT_2026_06_24_OK" in doc
print("SELECTED_DOMAIN_UNCONDITIONAL_CLOSURE_CONSTRUCTION_INPUT_2026_06_24_OK")
