from pathlib import Path
lean = Path("lean/Chronos/Frontier/SelectedDomainUnconditionalClosureSolvedFromConstructorTarget.lean").read_text()
artifact = Path("artifacts/external_validation/selected_domain_unconditional_closure_solved_from_constructor_target_2026_06_24.json").read_text()
doc = Path("docs/status/SELECTED_DOMAIN_UNCONDITIONAL_CLOSURE_SOLVED_FROM_CONSTRUCTOR_TARGET_2026_06_24.md").read_text()
assert "SelectedDomainUnconditionalUnrestrictedOblivionAtomClosureSolvedFromConstructorTarget" in lean and "SelectedDomainUnconditionalUnrestrictedOblivionAtomClosureSolvedFromConstructorTarget" in artifact and "SelectedDomainUnconditionalUnrestrictedOblivionAtomClosureSolvedFromConstructorTarget" in doc
assert "SelectedDomainUnconditionalClosureConstructorTarget" in lean and "SelectedDomainUnconditionalClosureConstructorTarget" in artifact and "SelectedDomainUnconditionalClosureConstructorTarget" in doc
assert "constructor_target" in lean and "constructor_target" in artifact and "constructor_target" in doc
assert "selected_domain_constructor_target_from_unconditional_solved_surface" in lean
assert "selected_domain_unconditional_closure_construction_input_from_solved_surface" in lean
assert "selected_domain_final_conditional_closure_bridge_from_solved_surface" in lean
assert "selected_domain_semantic_component_targets_from_solved_surface" in lean
assert "selected_domain_defect_atoms_target_from_solved_surface" in lean
assert "defect_atoms_construction_statement_from_solved_surface" in lean and "defect_atoms_construction_statement_from_solved_surface" in artifact and "defect_atoms_construction_statement_from_solved_surface" in doc
assert "unrestricted_oblivion_atom_closure_statement_from_solved_surface" in lean and "unrestricted_oblivion_atom_closure_statement_from_solved_surface" in artifact and "unrestricted_oblivion_atom_closure_statement_from_solved_surface" in doc
assert "selected_domain_unconditional_unrestricted_oblivion_atom_closure_solved_if_constructor_target_constructed" in lean and "selected_domain_unconditional_unrestricted_oblivion_atom_closure_solved_if_constructor_target_constructed" in artifact and "selected_domain_unconditional_unrestricted_oblivion_atom_closure_solved_if_constructor_target_constructed" in doc
assert "BOUNDARY := not selected_domain_unconditional_closure_constructor_target_constructed" in artifact and "BOUNDARY := not selected_domain_unconditional_closure_constructor_target_constructed" in doc
assert "BOUNDARY := not unconditional_unrestricted_oblivion_atom_closure_solved" in artifact and "BOUNDARY := not unconditional_unrestricted_oblivion_atom_closure_solved" in doc
assert "does not construct SelectedDomainUnconditionalClosureConstructorTarget" in doc
assert "does not prove unconditional unrestricted Oblivion Atom closure" in doc
assert "if the constructor target is supplied" in doc
assert "SELECTED_DOMAIN_UNCONDITIONAL_CLOSURE_SOLVED_FROM_CONSTRUCTOR_TARGET_2026_06_24_OK" in doc
print("SELECTED_DOMAIN_UNCONDITIONAL_CLOSURE_SOLVED_FROM_CONSTRUCTOR_TARGET_2026_06_24_OK")
