from pathlib import Path
lean = Path("lean/Chronos/Frontier/SelectedDomainUnconditionalClosureConstructorObligationMatrix.lean").read_text()
artifact = Path("artifacts/external_validation/selected_domain_unconditional_closure_constructor_obligation_matrix_2026_06_24.json").read_text()
doc = Path("docs/status/SELECTED_DOMAIN_UNCONDITIONAL_CLOSURE_CONSTRUCTOR_OBLIGATION_MATRIX_2026_06_24.md").read_text()
assert "SelectedDomainUnconditionalClosureConstructorObligationMatrix" in lean and "SelectedDomainUnconditionalClosureConstructorObligationMatrix" in artifact and "SelectedDomainUnconditionalClosureConstructorObligationMatrix" in doc
assert "SelectedDomainUnconditionalClosureConstructorTarget" in lean and "SelectedDomainUnconditionalClosureConstructorTarget" in artifact and "SelectedDomainUnconditionalClosureConstructorTarget" in doc
assert "SelectedDomainUnconditionalClosureConstructionInput" in lean and "SelectedDomainUnconditionalClosureConstructionInput" in artifact and "SelectedDomainUnconditionalClosureConstructionInput" in doc
assert "SelectedDomainFinalConditionalClosureBridge" in lean and "SelectedDomainFinalConditionalClosureBridge" in artifact and "SelectedDomainFinalConditionalClosureBridge" in doc
assert "SelectedDomainDefectSemanticComponentTargets" in lean and "SelectedDomainDefectSemanticComponentTargets" in artifact and "SelectedDomainDefectSemanticComponentTargets" in doc
assert "SelectedDomainUnconditionalUnrestrictedOblivionAtomClosureSolvedFromConstructorTarget" in lean and "SelectedDomainUnconditionalUnrestrictedOblivionAtomClosureSolvedFromConstructorTarget" in artifact and "SelectedDomainUnconditionalUnrestrictedOblivionAtomClosureSolvedFromConstructorTarget" in doc
assert "semantic_prefix_constructor_target" in lean and "semantic_prefix_constructor_target" in artifact and "semantic_prefix_constructor_target" in doc
assert "defect_atoms_constructor_target" in lean and "defect_atoms_constructor_target" in artifact and "defect_atoms_constructor_target" in doc
assert "semantic_prefix_constructor_target_from_obligation_matrix" in lean
assert "defect_atoms_constructor_target_from_obligation_matrix" in lean
assert "selected_domain_unconditional_closure_constructor_target_from_obligation_matrix" in lean
assert "selected_domain_unconditional_closure_construction_input_from_obligation_matrix" in lean
assert "selected_domain_final_conditional_closure_bridge_from_obligation_matrix" in lean
assert "selected_domain_semantic_component_targets_from_obligation_matrix" in lean
assert "selected_domain_closure_solved_surface_from_obligation_matrix" in lean
assert "defect_atoms_construction_statement_from_obligation_matrix" in lean and "defect_atoms_construction_statement_from_obligation_matrix" in artifact and "defect_atoms_construction_statement_from_obligation_matrix" in doc
assert "terminal_cardinality_of_defect_atoms_from_obligation_matrix" in lean and "terminal_cardinality_of_defect_atoms_from_obligation_matrix" in artifact and "terminal_cardinality_of_defect_atoms_from_obligation_matrix" in doc
assert "zero_defects_imply_selected_domain_reentry_from_obligation_matrix" in lean and "zero_defects_imply_selected_domain_reentry_from_obligation_matrix" in artifact and "zero_defects_imply_selected_domain_reentry_from_obligation_matrix" in doc
assert "repair_step_decreases_or_preserves_defect_atoms_from_obligation_matrix" in lean and "repair_step_decreases_or_preserves_defect_atoms_from_obligation_matrix" in artifact and "repair_step_decreases_or_preserves_defect_atoms_from_obligation_matrix" in doc
assert "defect_atoms_transfer_through_terminal_normalization_from_obligation_matrix" in lean and "defect_atoms_transfer_through_terminal_normalization_from_obligation_matrix" in artifact and "defect_atoms_transfer_through_terminal_normalization_from_obligation_matrix" in doc
assert "selected_domain_unconditional_unrestricted_oblivion_atom_closure_solved_from_obligation_matrix" in lean and "selected_domain_unconditional_unrestricted_oblivion_atom_closure_solved_from_obligation_matrix" in artifact and "selected_domain_unconditional_unrestricted_oblivion_atom_closure_solved_from_obligation_matrix" in doc
assert "BOUNDARY := not selected_domain_unconditional_closure_constructor_obligation_matrix_constructed" in artifact and "BOUNDARY := not selected_domain_unconditional_closure_constructor_obligation_matrix_constructed" in doc
assert "BOUNDARY := not selected_domain_unconditional_closure_constructor_target_constructed_without_matrix" in artifact and "BOUNDARY := not selected_domain_unconditional_closure_constructor_target_constructed_without_matrix" in doc
assert "BOUNDARY := not unconditional_unrestricted_oblivion_atom_closure_solved" in artifact and "BOUNDARY := not unconditional_unrestricted_oblivion_atom_closure_solved" in doc
assert "does not construct SelectedDomainUnconditionalClosureConstructorObligationMatrix" in doc
assert "does not prove unconditional unrestricted Oblivion Atom closure" in doc
assert "Do not merge inside this command." in doc
assert "SELECTED_DOMAIN_UNCONDITIONAL_CLOSURE_CONSTRUCTOR_OBLIGATION_MATRIX_2026_06_24_OK" in doc
print("SELECTED_DOMAIN_UNCONDITIONAL_CLOSURE_CONSTRUCTOR_OBLIGATION_MATRIX_2026_06_24_OK")
